from pathlib import Path
import webbrowser
import base64
import html

from analise.ia import opinar_top_imovel
from analise.regiao import analisar_regiao_detalhada
from painel.indicadores import buscar_indicadores
from painel.ranking import buscar_top_oportunidades, buscar_todos_imoveis
from config import RELATORIOS_DIR


def _obter_logo_base64():
    caminho_logo = Path(__file__).parent / "assets" / "logo.png"
    if caminho_logo.exists():
        try:
            with open(caminho_logo, "rb") as f:
                dados = base64.b64encode(f.read()).decode("utf-8")
                return f"data:image/png;base64,{dados}"
        except Exception:
            pass
    return None


def _montar_barras(indicadores):
    categorias = [
        ("Excelente", indicadores.get("excelentes", 0), "#22c55e"),
        ("Boa", indicadores.get("boas", 0), "#3b82f6"),
        ("Média", indicadores.get("medias", 0), "#f59e0b"),
        ("Baixa", indicadores.get("baixas", 0), "#ef4444"),
    ]
    total = max(sum(v for _, v, _ in categorias), 1)
    barras = []
    for nome, valor, cor in categorias:
        altura = max(8, int((valor / total) * 100))
        barras.append(
            f"<div class='bar-group'><div class='bar-label'>{nome} ({valor})</div><div class='bar-track'><div class='bar-fill' style='height:{altura}%; background:{cor};'></div></div></div>"
        )
    return "".join(barras)


def gerar_html_dashboard(caminho=None, tom_ia="equilibrado"):
    indicadores = buscar_indicadores()
    tom_ia = (tom_ia or "equilibrado").strip().lower()
    top_imoveis = buscar_top_oportunidades(10)
    todos_imoveis = buscar_todos_imoveis()
    logo_base64 = _obter_logo_base64()

    if caminho is None:
        caminho = RELATORIOS_DIR / "dashboard.html"

    RELATORIOS_DIR.mkdir(exist_ok=True, parents=True)

    linhas = []
    linhas.append("<!DOCTYPE html>")
    linhas.append("<html lang='pt-BR'>")
    linhas.append("<head>")
    linhas.append("  <meta charset='UTF-8'>")
    linhas.append("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
    linhas.append("  <title>Painel de Oportunidades</title>")
    linhas.append("  <style>")
    linhas.append("    :root { color-scheme: light; --navy: #0f172a; --gold: #c9a227; --cream: #f7f2e8; --line: #e7dfc7; }")
    linhas.append("    html, body { height: 100%; overflow: hidden; }")
    linhas.append("    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 10px; background: linear-gradient(135deg, #07111f, #12233f 45%, #1c3b5d); color: #0f172a; box-sizing: border-box; }")
    linhas.append("    .app { height: calc(100vh - 20px); display: flex; flex-direction: column; gap: 10px; overflow: hidden; }")
    linhas.append("    .card { background: linear-gradient(135deg, #ffffff, var(--cream)); border-radius: 16px; padding: 14px; margin-bottom: 0; box-shadow: 0 12px 28px rgba(7, 17, 31, 0.14); border: 1px solid var(--line); }")
    linhas.append("    h1, h2 { margin-top: 0; color: var(--navy); }")
    linhas.append("    .hero { display: flex; justify-content: center; align-items: center; gap: 16px; flex-wrap: wrap; }")
    linhas.append("    .brand { display: flex; justify-content: center; align-items: center; }")
    linhas.append("    .logo-img { width: 200px; height: auto; border-radius: 12px; object-fit: contain; box-shadow: 0 20px 40px rgba(201, 162, 39, 0.3); }")
    linhas.append("    .brand-mark { width: 54px; height: 54px; border-radius: 50%; background: linear-gradient(135deg, var(--gold), #f2d36b); display: flex; align-items: center; justify-content: center; color: var(--navy); font-weight: 700; box-shadow: 0 10px 20px rgba(201, 162, 39, 0.25); }")
    linhas.append("    .subtitle { margin: 4px 0 0; color: #475569; font-size: 0.95rem; }")
    linhas.append("    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }")
    linhas.append("    .metric { background: linear-gradient(135deg, #fffdf8, #f9f1d8); padding: 14px; border-radius: 12px; border: 1px solid var(--line); }")
    linhas.append("    .metric strong { display: block; font-size: 1.2rem; margin-bottom: 4px; }")
    linhas.append("    table { width: 100%; border-collapse: collapse; }")
    linhas.append("    th, td { text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0; }")
    linhas.append("    th { background: #e2e8f0; }")
    linhas.append("    .badge { display: inline-block; padding: 4px 8px; border-radius: 999px; font-size: 12px; font-weight: bold; }")
    linhas.append("    .Excelente { background: #dcfce7; color: #166534; }")
    linhas.append("    .Boa { background: #dbeafe; color: #1d4ed8; }")
    linhas.append("    .Média { background: #fef3c7; color: #92400e; }")
    linhas.append("    .Baixa { background: #fee2e2; color: #991b1b; }")
    linhas.append("    .bars { display: flex; align-items: flex-end; gap: 12px; min-height: 180px; margin-top: 12px; }")
    linhas.append("    .bar-group { flex: 1; display: flex; flex-direction: column; align-items: center; }")
    linhas.append("    .bar-track { width: 100%; max-width: 70px; height: 120px; background: #e2e8f0; border-radius: 999px; display: flex; align-items: flex-end; overflow: hidden; }")
    linhas.append("    .bar-fill { width: 100%; border-radius: 999px; }")
    linhas.append("    .bar-label { font-size: 12px; margin-bottom: 6px; color: #334155; }")
    linhas.append("    .btn { display: inline-block; padding: 10px 16px; background: linear-gradient(135deg, var(--navy), #234063); color: white; text-decoration: none; border-radius: 999px; margin-top: 8px; font-weight: 600; }")
    linhas.append("    .btn:disabled { opacity: 0.6; cursor: not-allowed; }")
    linhas.append("    .status-box { margin-top: 12px; padding: 12px; border-radius: 10px; border: 1px solid #cbd5e1; background: #f8fafc; color: #0f172a; }")
    linhas.append("    .status-box strong { display: block; margin-bottom: 6px; }")
    linhas.append("    .status-ok { border-color: #86efac; background: #f0fdf4; color: #14532d; }")
    linhas.append("    .status-erro { border-color: #fca5a5; background: #fef2f2; color: #7f1d1d; }")
    linhas.append("    .control-row { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }")
    linhas.append("    .tom-select { border: 1px solid #cbd5e1; background: #fff; color: #0f172a; border-radius: 10px; padding: 8px 10px; font-weight: 600; }")
    linhas.append("    .btn-secondary { display: inline-block; padding: 10px 16px; background: #ffffff; color: #0f172a; border: 1px solid #cbd5e1; text-decoration: none; border-radius: 999px; margin-top: 8px; font-weight: 600; cursor: pointer; }")
    linhas.append("    .progress-wrap { margin-top: 10px; }")
    linhas.append("    .progress-track { width: 100%; height: 12px; background: #e2e8f0; border-radius: 999px; overflow: hidden; }")
    linhas.append("    .progress-fill { height: 100%; width: 0%; background: linear-gradient(90deg, #0f766e, #3b82f6); transition: width 0.3s ease; }")
    linhas.append("    .progress-text { margin-top: 6px; font-size: 12px; color: #334155; }")
    linhas.append("    .etapas { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 8px; margin-top: 10px; }")
    linhas.append("    .etapa { font-size: 12px; border: 1px solid #cbd5e1; border-radius: 10px; padding: 8px; background: #fff; color: #334155; }")
    linhas.append("    .etapa.executando { border-color: #93c5fd; background: #eff6ff; color: #1e3a8a; }")
    linhas.append("    .etapa.concluida { border-color: #86efac; background: #f0fdf4; color: #14532d; }")
    linhas.append("    .etapa.erro { border-color: #fca5a5; background: #fef2f2; color: #7f1d1d; }")
    linhas.append("    .tabs { display: flex; gap: 8px; margin-bottom: 12px; flex-wrap: wrap; }")
    linhas.append("    .tab-btn { border: 1px solid #cbd5e1; background: #fff; color: #0f172a; border-radius: 999px; padding: 8px 14px; cursor: pointer; font-weight: 600; }")
    linhas.append("    .tab-btn.active { background: #0f172a; color: #fff; border-color: #0f172a; }")
    linhas.append("    .tab-pane { display: none; }")
    linhas.append("    .tab-pane.active { display: block; }")
    linhas.append("    .ia-lista { margin: 0; padding-left: 18px; }")
    linhas.append("    .ia-lista li { margin-bottom: 10px; line-height: 1.45; }")
    linhas.append("    .section-tabs { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 10px; }")
    linhas.append("    .section-btn { border: 1px solid #cbd5e1; background: #fff; color: #0f172a; border-radius: 999px; padding: 6px 12px; cursor: pointer; font-weight: 700; font-size: 12px; }")
    linhas.append("    .section-btn.active { background: #0f172a; color: #fff; border-color: #0f172a; }")
    linhas.append("    .section { display: none; min-height: 0; }")
    linhas.append("    .section.active { display: block; }")
    linhas.append("    #sec-resumo { flex: 1; min-height: 0; overflow: hidden; }")
    linhas.append("    #sec-top, #sec-todos { flex: 1; min-height: 0; overflow: hidden; }")
    linhas.append("    .table-scroll { max-height: 52vh; overflow: auto; border: 1px solid #d8dee9; border-radius: 10px; background: #fff; }")
    linhas.append("    #sec-resumo .card { margin-bottom: 10px; }")
    linhas.append("    @media (max-height: 800px) { .table-scroll { max-height: 45vh; } .bar-track { height: 90px; } }")
    linhas.append("    .link-analise { color: #0f4c81; font-weight: 600; text-decoration: underline; cursor: pointer; background: none; border: none; padding: 0; }")
    linhas.append("    .modal-overlay { position: fixed; inset: 0; background: rgba(2, 6, 23, 0.6); display: none; align-items: center; justify-content: center; z-index: 1000; }")
    linhas.append("    .modal-overlay.open { display: flex; }")
    linhas.append("    .modal-card { width: min(760px, 92vw); max-height: 80vh; overflow: auto; background: #fff; border-radius: 16px; border: 1px solid #cbd5e1; padding: 16px; box-shadow: 0 20px 60px rgba(15, 23, 42, 0.35); }")
    linhas.append("    .modal-card h3 { margin-top: 0; color: var(--navy); }")
    linhas.append("    .modal-close { float: right; border: 1px solid #cbd5e1; background: #fff; border-radius: 999px; padding: 4px 10px; cursor: pointer; }")
    linhas.append("    .modal-texto { white-space: pre-line; line-height: 1.45; color: #1e293b; }")
    linhas.append("    .modal-badges { display: flex; gap: 8px; flex-wrap: wrap; margin: 10px 0 8px; }")
    linhas.append("    .chip { display: inline-block; border-radius: 999px; padding: 5px 10px; font-size: 12px; font-weight: 700; border: 1px solid transparent; }")
    linhas.append("    .chip.neutro { background: #f1f5f9; color: #0f172a; border-color: #cbd5e1; }")
    linhas.append("    .chip.bom { background: #dcfce7; color: #166534; border-color: #86efac; }")
    linhas.append("    .chip.medio { background: #fef3c7; color: #92400e; border-color: #fde68a; }")
    linhas.append("    .chip.ruim { background: #fee2e2; color: #991b1b; border-color: #fca5a5; }")
    linhas.append("  </style>")
    linhas.append("</head>")
    linhas.append("<body>")
    linhas.append("  <div class='app'>")
    linhas.append("  <div class='card hero'>")
    linhas.append("    <div class='brand'>")
    if logo_base64:
        linhas.append(f"      <img src='{logo_base64}' alt='Arlete Galdino - Corretora de Imóveis' class='logo-img'>")
    else:
        linhas.append("      <div style='text-align: center;'><h1>Arlete Galdino</h1><p>Corretora de Imóveis</p></div>")
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  <div class='card'>")
    linhas.append("    <h2>Controle de captura</h2>")
    linhas.append("    <div class='control-row'>")
    linhas.append("      <button id='btn-captura' class='btn'>Iniciar captura</button>")
    linhas.append("      <button id='btn-nova-porta' class='btn-secondary'>Abrir em outra porta</button>")
    linhas.append("      <label for='tom-ia'><strong>Tom da IA:</strong></label>")
    linhas.append("      <select id='tom-ia' class='tom-select'>")
    linhas.append("        <option value='conservador'>Conservador</option>")
    linhas.append("        <option value='equilibrado' selected>Equilibrado</option>")
    linhas.append("        <option value='agressivo'>Agressivo</option>")
    linhas.append("      </select>")
    linhas.append("    </div>")
    linhas.append("    <div class='section-tabs'>")
    linhas.append("      <button class='section-btn active' data-section='sec-resumo'>Resumo</button>")
    linhas.append("      <button class='section-btn' data-section='sec-top'>Top</button>")
    linhas.append("      <button class='section-btn' data-section='sec-todos'>Todos</button>")
    linhas.append("    </div>")
    linhas.append("    <div id='status-captura' class='status-box'><strong>Status:</strong>Pronto para iniciar.</div>")
    linhas.append("    <div class='progress-wrap'>")
    linhas.append("      <div class='progress-track'><div id='progresso-fill' class='progress-fill'></div></div>")
    linhas.append("      <div id='progresso-texto' class='progress-text'>0% • aguardando início</div>")
    linhas.append("      <div id='etapas-captura' class='etapas'></div>")
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  <div id='sec-resumo' class='section active'>")
    linhas.append("  <div class='card'>")
    linhas.append("    <div class='grid'>")
    linhas.append(f"      <div class='metric'><strong>{indicadores['total']}</strong><br>Imóveis cadastrados</div>")
    linhas.append(f"      <div class='metric'><strong>R$ {indicadores['media_valor']:,.2f}</strong><br>Valor médio</div>")
    linhas.append(f"      <div class='metric'><strong>{indicadores['excelentes']}</strong><br>Excelente</div>")
    linhas.append(f"      <div class='metric'><strong>{indicadores['boas']}</strong><br>Boa</div>")
    linhas.append(f"      <div class='metric'><strong>{indicadores.get('medias', 0)}</strong><br>Média</div>")
    linhas.append(f"      <div class='metric'><strong>{indicadores.get('baixas', 0)}</strong><br>Baixa</div>")
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  <div class='card'>")
    linhas.append("    <h2>Distribuição por classificação</h2>")
    linhas.append("    <div class='bars'>")
    linhas.append(_montar_barras(indicadores))
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  </div>")
    linhas.append("  <div id='sec-top' class='section'>")
    linhas.append("  <div class='card'>")
    linhas.append("    <h2>Top oportunidades</h2>")
    linhas.append("    <div class='tabs'>")
    linhas.append("      <button class='tab-btn active' data-tab='tab-top-tabela'>Tabela</button>")
    linhas.append("      <button class='tab-btn' data-tab='tab-top-ia'>Comentários IA</button>")
    linhas.append("    </div>")
    linhas.append("    <div id='tab-top-tabela' class='tab-pane active'>")
    linhas.append("    <div class='table-scroll'>")
    linhas.append("    <table>")
    linhas.append("      <tr><th>Imóvel</th><th>Bairro</th><th>Valor</th><th>Pontuação</th><th>Classificação</th><th>Portal</th><th>Região</th></tr>")

    for titulo, bairro, valor, pontuacao, classificacao, portal, link in top_imoveis:
        titulo_exibicao = (titulo or "").strip() or "Sem título"
        bairro_exibicao = (bairro or "").strip() or "Não informado"
        classe_exibicao = (classificacao or "").strip() or "Baixa"
        dados_regiao = analisar_regiao_detalhada(bairro_exibicao, valor=valor, tipo=titulo_exibicao)
        analise_regiao = html.escape(
            "\n".join(
                [
                    dados_regiao["resumo"],
                    f"Tendência do bairro: {dados_regiao['tendencia']}",
                    f"Risco comercial: {dados_regiao['risco_comercial']}",
                    f"Recomendação de ação: {dados_regiao['recomendacao']}",
                ]
            ),
            quote=True,
        )
        linhas.append("      <tr>")
        linhas.append(f"        <td><a href='{link}' target='_blank'>{titulo_exibicao}</a></td>")
        linhas.append(f"        <td>{bairro_exibicao}</td>")
        linhas.append(f"        <td>R$ {valor:,.2f}</td>")
        linhas.append(f"        <td>{pontuacao}</td>")
        linhas.append(f"        <td><span class='badge {classe_exibicao}'>{classe_exibicao}</span></td>")
        linhas.append(f"        <td>{portal}</td>")
        linhas.append(f"        <td><button class='link-analise' data-analise='{analise_regiao}'>Ver análise</button></td>")
        linhas.append("      </tr>")

    linhas.append("    </table>")
    linhas.append("    </div>")
    linhas.append("    </div>")
    linhas.append("    <div id='tab-top-ia' class='tab-pane'>")
    linhas.append(f"      <p><strong>Tom atual da IA:</strong> {tom_ia.title()}</p>")
    linhas.append("      <ol class='ia-lista'>")
    for titulo, bairro, valor, pontuacao, classificacao, portal, _ in top_imoveis:
        comentario = opinar_top_imovel(
            titulo=titulo,
            bairro=bairro,
            valor=valor,
            pontuacao=pontuacao,
            classificacao=classificacao,
            portal=portal,
            tom=tom_ia,
        ).replace("'", "&#39;")
        linhas.append(f"        <li>{comentario}</li>")
    linhas.append("      </ol>")
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  </div>")
    linhas.append("  <div id='sec-todos' class='section'>")
    linhas.append("  <div class='card'>")
    linhas.append("    <h2>Todos os imóveis captados</h2>")
    linhas.append("    <div class='table-scroll'>")
    linhas.append("    <table>")
    linhas.append("      <tr><th>Imóvel</th><th>Bairro</th><th>Valor</th><th>Pontuação</th><th>Classificação</th><th>Portal</th><th>Região</th></tr>")

    for titulo, bairro, valor, pontuacao, classificacao, portal, link in todos_imoveis:
        titulo_exibicao = (titulo or "").strip() or "Sem título"
        bairro_exibicao = (bairro or "").strip() or "Não informado"
        classe_exibicao = (classificacao or "").strip() or "Baixa"
        dados_regiao = analisar_regiao_detalhada(bairro_exibicao, valor=valor, tipo=titulo_exibicao)
        analise_regiao = html.escape(
            "\n".join(
                [
                    dados_regiao["resumo"],
                    f"Tendência do bairro: {dados_regiao['tendencia']}",
                    f"Risco comercial: {dados_regiao['risco_comercial']}",
                    f"Recomendação de ação: {dados_regiao['recomendacao']}",
                ]
            ),
            quote=True,
        )
        linhas.append("      <tr>")
        linhas.append(f"        <td><a href='{link}' target='_blank'>{titulo_exibicao}</a></td>")
        linhas.append(f"        <td>{bairro_exibicao}</td>")
        linhas.append(f"        <td>R$ {valor:,.2f}</td>")
        linhas.append(f"        <td>{pontuacao}</td>")
        linhas.append(f"        <td><span class='badge {classe_exibicao}'>{classe_exibicao}</span></td>")
        linhas.append(f"        <td>{portal}</td>")
        linhas.append(f"        <td><button class='link-analise' data-analise='{analise_regiao}'>Ver análise</button></td>")
        linhas.append("      </tr>")

    linhas.append("    </table>")
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  <div id='modal-regiao' class='modal-overlay'>")
    linhas.append("    <div class='modal-card'>")
    linhas.append("      <button id='modal-close' class='modal-close'>Fechar</button>")
    linhas.append("      <h3>Análise da região e mercado imobiliário</h3>")
    linhas.append("      <div id='modal-texto' class='modal-texto'></div>")
    linhas.append("    </div>")
    linhas.append("  </div>")
    linhas.append("  </div>")
    linhas.append("  <script>")
    linhas.append("    const btn = document.getElementById('btn-captura');")
    linhas.append("    const statusBox = document.getElementById('status-captura');")
    linhas.append("    const progressoFill = document.getElementById('progresso-fill');")
    linhas.append("    const progressoTexto = document.getElementById('progresso-texto');")
    linhas.append("    const etapasContainer = document.getElementById('etapas-captura');")
    linhas.append("    const btnNovaPorta = document.getElementById('btn-nova-porta');")
    linhas.append("    const tomIaSelect = document.getElementById('tom-ia');")
    linhas.append("    const tabButtons = document.querySelectorAll('.tab-btn');")
    linhas.append("    const sectionButtons = document.querySelectorAll('.section-btn');")
    linhas.append("    const linksAnalise = document.querySelectorAll('.link-analise');")
    linhas.append("    const modalRegiao = document.getElementById('modal-regiao');")
    linhas.append("    const modalTexto = document.getElementById('modal-texto');")
    linhas.append("    const modalClose = document.getElementById('modal-close');")
    linhas.append("    let polling = null;")
    linhas.append("    let finalizado = false;")
    linhas.append("    let ultimoStatus = null;")
    linhas.append("")
    linhas.append("    function renderResumo(resumo) {")
    linhas.append("      if (!resumo) return ''; ")
    linhas.append("      return [")
    linhas.append("        'Captura finalizada com sucesso.',")
    linhas.append("        'Anúncios capturados: ' + resumo.anuncios_capturados,")
    linhas.append("        'Imóveis processados: ' + resumo.imoveis_processados,")
    linhas.append("        'Novos imóveis salvos: ' + resumo.novos_salvos,")
    linhas.append("        'Registros descartados: ' + resumo.descartados,")
    linhas.append("        'Falhas de abertura: ' + resumo.falhas_abertura,")
    linhas.append("        'Qualidade média dos dados: ' + resumo.score_qualidade_medio,")
    linhas.append("        'Execução: ' + (resumo.run_id || '-')")
    linhas.append("      ].join('<br>');")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function nomeEtapa(nome) {")
    linhas.append("      const mapa = {")
    linhas.append("        captura: 'Captura',")
    linhas.append("        extracao: 'Extração',")
    linhas.append("        classificacao: 'Classificação',")
    linhas.append("        exportacao: 'Exportação',")
    linhas.append("        dashboard: 'Dashboard'")
    linhas.append("      };")
    linhas.append("      return mapa[nome] || nome;")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function renderProgresso(progresso) {")
    linhas.append("      const pct = (progresso && Number.isFinite(progresso.percentual)) ? progresso.percentual : 0;")
    linhas.append("      const msg = (progresso && progresso.mensagem) ? progresso.mensagem : 'Aguardando início.';")
    linhas.append("      progressoFill.style.width = `${pct}%`;")
    linhas.append("      progressoTexto.textContent = `${pct}% • ${msg}`;")
    linhas.append("      const etapas = (progresso && Array.isArray(progresso.etapas)) ? progresso.etapas : []; ")
    linhas.append("      if (!etapas.length) {")
    linhas.append("        etapasContainer.innerHTML = '';")
    linhas.append("        return;")
    linhas.append("      }")
    linhas.append("      etapasContainer.innerHTML = etapas.map(e => `")
    linhas.append("        <div class='etapa ${e.status || 'pendente'}'>")
    linhas.append("          <strong>${nomeEtapa(e.nome)}</strong>")
    linhas.append("          <div>${(e.status || 'pendente').replace('concluida','concluída')}</div>")
    linhas.append("        </div>")
    linhas.append("      `).join('');")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function classeBadgeTendencia(valor) {")
    linhas.append("      if (valor === 'alta' || valor === 'oportunidade') return 'bom';")
    linhas.append("      if (valor === 'estável' || valor === 'estavel') return 'medio';")
    linhas.append("      return 'neutro';")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function classeBadgeRisco(valor) {")
    linhas.append("      if (valor === 'baixo') return 'bom';")
    linhas.append("      if (valor === 'médio' || valor === 'medio') return 'medio';")
    linhas.append("      if (valor === 'alto') return 'ruim';")
    linhas.append("      return 'neutro';")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function classeBadgeAcao(valor) {")
    linhas.append("      if (valor === 'abordar agora') return 'bom';")
    linhas.append("      if (valor === 'monitorar') return 'medio';")
    linhas.append("      if (valor === 'aguardar ajuste de preço' || valor === 'aguardar ajuste de preco') return 'ruim';")
    linhas.append("      return 'neutro';")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function atualizarStatus() {")
    linhas.append("      fetch('/api/captura/status')")
    linhas.append("        .then(r => r.json())")
    linhas.append("        .then(data => {")
    linhas.append("          if (data.status === 'executando') {")
    linhas.append("            ultimoStatus = 'executando';")
    linhas.append("            btn.disabled = true;")
    linhas.append("            statusBox.className = 'status-box';")
    linhas.append("            statusBox.innerHTML = '<strong>Status:</strong>Captura em execução... Atualização automática ao finalizar.';")
    linhas.append("            renderProgresso(data.progresso);")
    linhas.append("            return;")
    linhas.append("          }")
    linhas.append("")
    linhas.append("          if (data.status === 'concluido') {")
    linhas.append("            btn.disabled = false;")
    linhas.append("            statusBox.className = 'status-box status-ok';")
    linhas.append("            statusBox.innerHTML = '<strong>Concluído</strong>' + renderResumo(data.resumo);")
    linhas.append("            renderProgresso(data.progresso);")
    linhas.append("            if (!finalizado && ultimoStatus === 'executando') {")
    linhas.append("              finalizado = true;")
    linhas.append("              setTimeout(() => location.reload(), 1200);")
    linhas.append("            }")
    linhas.append("            ultimoStatus = 'concluido';")
    linhas.append("            if (polling) { clearInterval(polling); polling = null; }")
    linhas.append("            return;")
    linhas.append("          }")
    linhas.append("")
    linhas.append("          if (data.status === 'erro') {")
    linhas.append("            ultimoStatus = 'erro';")
    linhas.append("            btn.disabled = false;")
    linhas.append("            statusBox.className = 'status-box status-erro';")
    linhas.append("            statusBox.innerHTML = '<strong>Erro na captura</strong>' + (data.erro || 'Falha sem detalhes.');")
    linhas.append("            renderProgresso(data.progresso);")
    linhas.append("            if (polling) { clearInterval(polling); polling = null; }")
    linhas.append("            return;")
    linhas.append("          }")
    linhas.append("")
    linhas.append("          btn.disabled = false;")
    linhas.append("          statusBox.className = 'status-box';")
    linhas.append("          statusBox.innerHTML = '<strong>Status:</strong>Pronto para iniciar.';")
    linhas.append("          renderProgresso(data.progresso);")
    linhas.append("          ultimoStatus = data.status || 'ocioso';")
    linhas.append("        })")
    linhas.append("        .catch(() => {")
    linhas.append("          btn.disabled = false;")
    linhas.append("          statusBox.className = 'status-box status-erro';")
    linhas.append("          statusBox.innerHTML = '<strong>API indisponível</strong>Inicie com: python -m painel.webapp';")
    linhas.append("          renderProgresso({ percentual: 0, mensagem: 'API indisponível', etapas: [] });")
    linhas.append("          if (polling) { clearInterval(polling); polling = null; }")
    linhas.append("        });")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function carregarTomIa() {")
    linhas.append("      fetch('/api/ia/tom')")
    linhas.append("        .then(r => r.json())")
    linhas.append("        .then(data => {")
    linhas.append("          if (data && data.tom) tomIaSelect.value = data.tom;")
    linhas.append("        })")
    linhas.append("        .catch(() => {});")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    function ativarSecao(secaoId) {")
    linhas.append("      document.querySelectorAll('.section').forEach(sec => sec.classList.remove('active'));")
    linhas.append("      document.querySelectorAll('.section-btn').forEach(btnSec => btnSec.classList.remove('active'));")
    linhas.append("      const secao = document.getElementById(secaoId);")
    linhas.append("      if (secao) secao.classList.add('active');")
    linhas.append("      const botao = document.querySelector(`.section-btn[data-section='${secaoId}']`);")
    linhas.append("      if (botao) botao.classList.add('active');")
    linhas.append("    }")
    linhas.append("")
    linhas.append("    btn.addEventListener('click', () => {")
    linhas.append("      finalizado = false;")
    linhas.append("      btn.disabled = true;")
    linhas.append("      statusBox.className = 'status-box';")
    linhas.append("      statusBox.innerHTML = '<strong>Status:</strong>Solicitando início da captura...';")
    linhas.append("      renderProgresso({ percentual: 2, mensagem: 'Solicitando início...', etapas: [")
    linhas.append("        {nome:'captura', status:'executando'},")
    linhas.append("        {nome:'extracao', status:'pendente'},")
    linhas.append("        {nome:'classificacao', status:'pendente'},")
    linhas.append("        {nome:'exportacao', status:'pendente'},")
    linhas.append("        {nome:'dashboard', status:'pendente'}")
    linhas.append("      ]});")
    linhas.append("")
    linhas.append("      fetch('/api/captura/iniciar', { method: 'POST' })")
    linhas.append("        .then(async r => ({ ok: r.ok, data: await r.json() }))")
    linhas.append("        .then(({ ok, data }) => {")
    linhas.append("          if (!ok) {")
    linhas.append("            btn.disabled = false;")
    linhas.append("            statusBox.className = 'status-box status-erro';")
    linhas.append("            statusBox.innerHTML = '<strong>Não foi possível iniciar</strong>' + (data.mensagem || '');")
    linhas.append("            return;")
    linhas.append("          }")
    linhas.append("          atualizarStatus();")
    linhas.append("          polling = setInterval(atualizarStatus, 2500);")
    linhas.append("        })")
    linhas.append("        .catch(() => {")
    linhas.append("          btn.disabled = false;")
    linhas.append("          statusBox.className = 'status-box status-erro';")
    linhas.append("          statusBox.innerHTML = '<strong>Falha de comunicação</strong>Não foi possível chamar a API local.';")
    linhas.append("        });")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    tabButtons.forEach(btnTab => {")
    linhas.append("      btnTab.addEventListener('click', () => {")
    linhas.append("        const target = btnTab.getAttribute('data-tab');")
    linhas.append("        document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));")
    linhas.append("        document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));")
    linhas.append("        btnTab.classList.add('active');")
    linhas.append("        const pane = document.getElementById(target);")
    linhas.append("        if (pane) pane.classList.add('active');")
    linhas.append("      });")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    sectionButtons.forEach(btnSec => {")
    linhas.append("      btnSec.addEventListener('click', () => {")
    linhas.append("        ativarSecao(btnSec.getAttribute('data-section'));")
    linhas.append("      });")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    linksAnalise.forEach(linkAnalise => {")
    linhas.append("      linkAnalise.addEventListener('click', () => {")
    linhas.append("        const texto = linkAnalise.getAttribute('data-analise') || 'Análise indisponível.';")
    linhas.append("        const partes = texto.split('\\n');")
    linhas.append("        const tendencia = (partes.find(p => p.startsWith('Tendência do bairro:')) || '').replace('Tendência do bairro:', '').trim();")
    linhas.append("        const risco = (partes.find(p => p.startsWith('Risco comercial:')) || '').replace('Risco comercial:', '').trim();")
    linhas.append("        const acao = (partes.find(p => p.startsWith('Recomendação de ação:')) || '').replace('Recomendação de ação:', '').trim();")
    linhas.append("        const resumo = partes.filter(p => !p.startsWith('Tendência do bairro:') && !p.startsWith('Risco comercial:') && !p.startsWith('Recomendação de ação:')).join('\\n').trim();")
    linhas.append("        modalTexto.innerHTML = `")
    linhas.append("          <div class='modal-badges'>")
    linhas.append("            <span class='chip ${classeBadgeTendencia(tendencia)}'>Tendência: ${tendencia || '-'}</span>")
    linhas.append("            <span class='chip ${classeBadgeRisco(risco)}'>Risco: ${risco || '-'}</span>")
    linhas.append("            <span class='chip ${classeBadgeAcao(acao)}'>Ação: ${acao || '-'}</span>")
    linhas.append("          </div>")
    linhas.append("          <div>${resumo || 'Análise indisponível.'}</div>")
    linhas.append("        `;")
    linhas.append("        modalRegiao.classList.add('open');")
    linhas.append("      });")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    modalClose.addEventListener('click', () => modalRegiao.classList.remove('open'));")
    linhas.append("    modalRegiao.addEventListener('click', (ev) => {")
    linhas.append("      if (ev.target === modalRegiao) modalRegiao.classList.remove('open');")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    tomIaSelect.addEventListener('change', () => {")
    linhas.append("      const tom = tomIaSelect.value;")
    linhas.append("      tomIaSelect.disabled = true;")
    linhas.append("      fetch('/api/ia/tom', {")
    linhas.append("        method: 'POST',")
    linhas.append("        headers: { 'Content-Type': 'application/json' },")
    linhas.append("        body: JSON.stringify({ tom })")
    linhas.append("      })")
    linhas.append("      .then(async r => ({ ok: r.ok, data: await r.json() }))")
    linhas.append("      .then(({ ok, data }) => {")
    linhas.append("        tomIaSelect.disabled = false;")
    linhas.append("        if (!ok) {")
    linhas.append("          statusBox.className = 'status-box status-erro';")
    linhas.append("          statusBox.innerHTML = '<strong>Tom não alterado</strong>' + (data.mensagem || '');")
    linhas.append("          return;")
    linhas.append("        }")
    linhas.append("        statusBox.className = 'status-box status-ok';")
    linhas.append("        statusBox.innerHTML = '<strong>Tom atualizado</strong>Comentários IA serão recarregados.';")
    linhas.append("        setTimeout(() => location.reload(), 500);")
    linhas.append("      })")
    linhas.append("      .catch(() => {")
    linhas.append("        tomIaSelect.disabled = false;")
    linhas.append("        statusBox.className = 'status-box status-erro';")
    linhas.append("        statusBox.innerHTML = '<strong>Falha de comunicação</strong>Não foi possível alterar o tom da IA.';")
    linhas.append("      });")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    btnNovaPorta.addEventListener('click', () => {")
    linhas.append("      btnNovaPorta.disabled = true;")
    linhas.append("      statusBox.className = 'status-box';")
    linhas.append("      statusBox.innerHTML = '<strong>Servidor</strong>Iniciando nova instância em outra porta...';")
    linhas.append("")
    linhas.append("      fetch('/api/server/nova-porta', { method: 'POST' })")
    linhas.append("        .then(async r => ({ ok: r.ok, data: await r.json() }))")
    linhas.append("        .then(({ ok, data }) => {")
    linhas.append("          btnNovaPorta.disabled = false;")
    linhas.append("          if (!ok) {")
    linhas.append("            statusBox.className = 'status-box status-erro';")
    linhas.append("            statusBox.innerHTML = '<strong>Falha ao abrir nova porta</strong>' + (data.mensagem || '');")
    linhas.append("            return;")
    linhas.append("          }")
    linhas.append("          statusBox.className = 'status-box status-ok';")
    linhas.append("          statusBox.innerHTML = `<strong>Nova instância iniciada</strong><a href='${data.url_dashboard}' target='_blank'>${data.url_dashboard}</a>`;")
    linhas.append("          window.open(data.url_dashboard, '_blank');")
    linhas.append("        })")
    linhas.append("        .catch(() => {")
    linhas.append("          btnNovaPorta.disabled = false;")
    linhas.append("          statusBox.className = 'status-box status-erro';")
    linhas.append("          statusBox.innerHTML = '<strong>Falha de comunicação</strong>Não foi possível iniciar outra porta.';")
    linhas.append("        });")
    linhas.append("    });")
    linhas.append("")
    linhas.append("    carregarTomIa();")
    linhas.append("    ativarSecao('sec-resumo');")
    linhas.append("    atualizarStatus();")
    linhas.append("  </script>")
    linhas.append("  </div>")
    linhas.append("</body>")
    linhas.append("</html>")

    caminho = Path(caminho)
    caminho.write_text("\n".join(linhas), encoding="utf-8")
    return caminho


def abrir_dashboard_html(caminho=None):
    caminho = gerar_html_dashboard(caminho)
    try:
        webbrowser.open(caminho.resolve().as_uri())
    except Exception:
        pass
    return caminho
